### ISSUE TITLE
Broken link not detectced

### ISSUE THREAD

**Issue by mmitoraj** [kyma-project/md-check-link#22]
**Description**

When clicking around the [`/documentation`](https://github.tools.sap/kyma/documentation) repo and the [kyma.int.sap](https://pages.github.tools.sap/kyma/documentation/#/modularization/README) website, I came across a broken link in [https://github.tools.sap/kyma/documentation/blob/main/modularization/README.md](https://github.tools.sap/kyma/documentation/blob/main/modularization/README.md) to [New Module - Admin Guide](https://github.tools.sap/kyma/module-manifests/blob/main/new_module_admin_guide.md). The link is broken but it was not detected by the `md-check-link` GitHub action. 

Can you help investigate why?

**Expected result**

Broken links detected

**Actual result**

The broken link was not detected by the `md-check-link` GitHub action.

**Steps to reproduce**

**Troubleshooting**

**Comment by pbochynski** [comment]
The link goes to the internal github that requires authentication. Returned status code is 302 and github redirects to login page (that exists). Not sure what to do with that. Let's first check how many links go to the internal github. If it just a few we can ignore the problem if it is many - we need special code that retrieves github token and uses it to fetch such link.

**Comment by pbochynski** [comment]
I found almost 200 links to github.tools.sap so we should handle them differently.

**Comment by pbochynski** [comment]
Some links lead to the same repository and can be replaced by relative links. Other links point to organizations, teams, issues, or other pages that cannot be fetched without authorizing the user (a GitHub token is not usable in such cases). 
Implementing user authentication/authorization flow would be too complex in comparison to benefits.
The recommendation is to use relative links wherever possible, consolidate documentation by moving content to the same repository, and avoid links to restricted content that require authorization.
